// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieOrder.API.Data;

#nullable disable

namespace MovieOrder.API.Migrations
{
    [DbContext(typeof(MovieOrderDbContext))]
    partial class MovieOrderDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MovieOrder.API.Entities.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("MovieOrder.API.Entities.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Qty")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Cartitems");
                });

            modelBuilder.Entity("MovieOrder.API.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Qty")
                        .HasColumnType("int");

                    b.Property<decimal>("price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "After being bestowed with godly powers and imprisoned for it, Black Adam is liberated from his earthly binds to unleash his fury on the modern world.",
                            ImageUrl = "/Images/Beauty/Beauty1.png",
                            Name = "Black Adam",
                            Qty = 100,
                            price = 10m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "After being bestowed with godly powers and imprisoned for it, Black Adam is liberated from his earthly binds to unleash his fury on the modern world.",
                            ImageUrl = "/Images/Beauty/Beauty1.png",
                            Name = "Black Panther: Wakanda forever",
                            Qty = 100,
                            price = 10m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Description = "Thor embarks on a journey unlike anything he's ever faced -- a quest for inner peace. However, his retirement gets interrupted by Gorr the God Butcher, a galactic killer who seeks the extinction of the gods. .",
                            ImageUrl = "/Images/Beauty/Beauty1.png",
                            Name = "Thor: Love and Thunder",
                            Qty = 100,
                            price = 12m
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Description = "Jake Sully and Ney'tiri have formed a family and are doing everything to stay together. However, they must leave their home and explore the regions of Pandora. When an ancient threat resurfaces, Jake must fight a difficult war against the humans.",
                            ImageUrl = "/Images/Beauty/Beauty1.png",
                            Name = "Avatar: The way of water",
                            Qty = 100,
                            price = 10m
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            Description = "A man and his ex-wife race to Bali, Indonesia, to stop their daughter from marrying a seaweed farmer. As they desperately try to sabotage the wedding, the bickering duo soon find themselves rekindling old feelings that once made them happy together.",
                            ImageUrl = "/Images/Beauty/Beauty1.png",
                            Name = "Ticket to Paradise",
                            Qty = 100,
                            price = 10m
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            Description = "Ladybug is an unlucky assassin who's determined to do his job peacefully after one too many gigs has gone off the rails.",
                            ImageUrl = "/Images/Beauty/Beauty1.png",
                            Name = "Bullet Train",
                            Qty = 100,
                            price = 10m
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            Description = "College professor Jack Gladney and his family's comfortable suburban life is upended when a nearby chemical leak causes \"The Airborne Toxic Event,\" releasing a noxious black cloud over the region that forces the Gladney family to evacuate.",
                            ImageUrl = "/Images/Beauty/Beauty1.png",
                            Name = "White Noise",
                            Qty = 100,
                            price = 10m
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            Description = "Ousmane and François are two cops with very different styles. The unlikely pair are reunited once again for a new investigation.",
                            ImageUrl = "/Images/Beauty/Beauty1.png",
                            Name = "The Takedown",
                            Qty = 100,
                            price = 10m
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 3,
                            Description = "A man and his ex-wife race to Bali, Indonesia, to stop their daughter from marrying a seaweed farmer. As they desperately try to sabotage the wedding, the bickering duo soon find themselves rekindling old feelings that once made them happy together.",
                            ImageUrl = "/Images/Beauty/Beauty1.png",
                            Name = "Ticket to Paradise",
                            Qty = 100,
                            price = 10m
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 3,
                            Description = "When Superman and the rest of the league get kidnapped by Lex Luthor, it is up to Superdog Krypto to rescue them. He finds a group of shelter pets with superpowers and convinces them to help him.",
                            ImageUrl = "/Images/Beauty/Beauty1.png",
                            Name = "DC League of Super-Pets",
                            Qty = 100,
                            price = 10m
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 3,
                            Description = "A man and his sister discover something sinister in the skies above their California horse ranch, while the owner of a nearby theme park tries to profit from the mysterious, otherworldly phenomenon..",
                            ImageUrl = "/Images/Beauty/Beauty1.png",
                            Name = "Nope",
                            Qty = 100,
                            price = 10m
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 3,
                            Description = "Two inmates form a connection while grappling with their pasts in a state-of-the-art penitentiary run by a brilliant visionary who experiments on his subjects with mind-altering drugs.",
                            ImageUrl = "/Images/Beauty/Beauty1.png",
                            Name = "Spiderhead",
                            Qty = 100,
                            price = 10m
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 4,
                            Description = "After witnessing a bizarre, traumatic incident involving a patient, Dr. Rose Cotter starts experiencing frightening occurrences that she can't explain.",
                            ImageUrl = "/Images/Beauty/Beauty1.png",
                            Name = "Smile",
                            Qty = 100,
                            price = 10m
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 4,
                            Description = "The film, penned by Will Tracy and Seth Reiss, focuses on a young couple who visits an exclusive destination restaurant on a remote island",
                            ImageUrl = "/Images/Beauty/Beauty1.png",
                            Name = "The Menu",
                            Qty = 100,
                            price = 10m
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 4,
                            Description = "After the death of her mother and having no other known relatives, Evie takes a DNA test and discovers a long-lost cousin she never knew she had.",
                            ImageUrl = "/Images/Beauty/Beauty1.png",
                            Name = "The Invitation",
                            Qty = 100,
                            price = 10m
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 4,
                            Description = "A filmmaking crew and the cast make an adult movie at a reclusive place but elderly hosts find them and try to kill them.",
                            ImageUrl = "/Images/Beauty/Beauty1.png",
                            Name = "X",
                            Qty = 100,
                            price = 10m
                        });
                });

            modelBuilder.Entity("MovieOrder.API.Entities.ProductCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProductCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Action"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Comedy"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Sci Fi"
                        },
                        new
                        {
                            Id = 4,
                            Name = "horror"
                        });
                });

            modelBuilder.Entity("MovieOrder.API.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
